pcm.shared_mic {
    type plug
    slave.pcm {
        type dsnoop
        ipc_key 1024
        slave {
            # Example, find your device with `arecord -L`
            pcm "hw:3,0"
            rate 48000
            channels 1
        }
    }
}
