[supervisord]
nodaemon=true
user=root
pidfile=/var/run/supervisord.pid
logfile=/var/log/supervisor/supervisord.log
childlogdir=/var/log/supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:birdnet

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:php-fpm]
command=/usr/local/bin/php-fpm -F
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
autostart=true
autorestart=true
user=root
stdout_logfile=/data/logs/caddy.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/caddy.log
stderr_logfile_maxbytes=10MB

[program:birdnet_analysis]
command=python3 /home/birdnet/BirdNET-Pi/scripts/birdnet_analysis.py
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/birdnet_analysis.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/birdnet_analysis.log
stderr_logfile_maxbytes=10MB

[program:birdnet_recording]
command=bash /usr/local/bin/birdnet_recording.sh
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/birdnet_recording.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/birdnet_recording.log
stderr_logfile_maxbytes=10MB

[program:birdnet_stats]
command=streamlit run /home/birdnet/BirdNET-Pi/scripts/plotly_streamlit.py --browser.gatherUsageStats false --server.address localhost --server.baseUrlPath "/stats"
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/birdnet_stats.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/birdnet_stats.log
stderr_logfile_maxbytes=10MB

[program:chart_viewer]
command=python3 /home/birdnet/BirdNET-Pi/scripts/daily_plot.py --daemon --sleep 2
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/chart_viewer.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/chart_viewer.log
stderr_logfile_maxbytes=10MB

[program:birdnet_log]
command=/usr/local/bin/gotty --address localhost -p 8080 --path log --title-format "BirdNET-Pi Log" /usr/local/bin/birdnet_log.sh
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/birdnet_log.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/birdnet_log.log
stderr_logfile_maxbytes=10MB

[program:web_terminal]
command=/usr/local/bin/gotty --address localhost -w -p 8888 --path terminal --title-format "BirdNET-Pi Terminal" bash
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/web_terminal.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/web_terminal.log
stderr_logfile_maxbytes=10MB

[program:spectrogram_viewer]
command=bash /usr/local/bin/spectrogram.sh
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/spectrogram_viewer.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/spectrogram_viewer.log
stderr_logfile_maxbytes=10MB

[program:icecast2]
command=icecast2 -c /etc/icecast2/icecast.xml
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/icecast2.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/icecast2.log
stderr_logfile_maxbytes=10MB

[program:livestream]
command=bash /usr/local/bin/livestream.sh
autostart=true
autorestart=true
user=birdnet
stdout_logfile=/data/logs/livestream.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/data/logs/livestream.log
stderr_logfile_maxbytes=10MB
